<a href="https://colab.research.google.com/github/makokhamj/Assignment1/blob/master/Python_ML_2021_02_24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello")

Hello


In [ ]:
import numpy
dataset = numpy.loadtxt('https://raw.githubusercontent.com/jakelever/swc-machine-learning-short/gh-pages/data/dataset.tsv',skiprows=1)

In [ ]:
print(type(dataset))

<class 'numpy.ndarray'>


In [ ]:
print(dataset.shape)

(500, 10)


In [ ]:
print(dataset[3,2])

168.0


In [ ]:
print(dataset[:5,:])

[[ 40.     2.   165.    44.     5.66  10.2    2.14   3.47   9.71   0.  ]
 [ 45.     1.   162.    73.     6.57   6.44   1.61   2.43   9.19   1.  ]
 [ 50.     1.   192.    91.     6.52   8.37   4.19   3.76   9.07   1.  ]
 [ 25.     2.   168.    64.     5.67   8.04   3.51   2.86  13.82   0.  ]
 [ 38.     1.   156.    37.     5.14  11.31   4.54   5.8    4.23   0.  ]]


In [ ]:
target = dataset[:,9]
features = dataset[:,0:9]

In [ ]:
print(target.shape)
print(features.shape)

(500,)
(500, 9)


In [ ]:
print(features[:,0].min())

25.0


In [ ]:
print(features.min(axis=0))

[ 25.     1.   138.    31.     2.46   1.88   0.08   0.96   0.61]


In [ ]:
numpy.set_printoptions(suppress=True)

In [ ]:
print(features.min(axis=0), features.max(axis=0), features.mean(axis=0))

[ 25.     1.   138.    31.     2.46   1.88   0.08   0.96   0.61] [ 64.     2.   207.   115.     9.7   13.93   6.71   6.92  18.52] [ 43.458     1.498   169.232    65.998     5.61906   8.19288   3.38444
   4.0199    9.07966]


In [ ]:
pos_count = target.sum()
N = target.shape[0]
class_balance = 100 * pos_count / N
print(pos_count, N)
print(class_balance)

155.0 500
31.0


In [ ]:
from sklearn.model_selection import train_test_split
features_train, features_test, target_train, target_test = train_test_split(features, target, test_size=0.2, random_state=0)
features_train, features_validation, target_train, target_validation = train_test_split(features_train, target_train, test_size=0.2, random_state=0)

print(features_train.shape)
print(features_validation.shape)
print(features_test.shape)

print(target_train.shape)
print(target_validation.shape)
print(target_test.shape)

N_train = target_train.shape[0]
N_validation = target_validation.shape[0]
N_test = target_test.shape[0]

(320, 9)
(80, 9)
(100, 9)
(320,)
(80,)
(100,)


In [ ]:
pred_train = []
for i in range(N_train):
  if features_train[i,3] > 75:
    pred_train.append(True)
  else:
    pred_train.append(False)

print(sum(pred_train),len(pred_train))

68 320


In [ ]:
matching = 0
for i in range(N_train):
  if pred_train[i] == target_train[i]:
    matching += 1

train_accuracy = matching / N_train
print(train_accuracy)

0.8625


In [ ]:
def calcAccuracy(target, pred):
  matching = 0
  for i in range(len(pred)):
    if pred[i] == target[i]:
      matching += 1
  accuracy = matching / len(pred)
  return accuracy

print(calcAccuracy(target_train,pred_train))

0.8625


In [ ]:
pred_validation = []
for i in range(N_validation):
  if features_validation[i,3] > 75:
    pred_validation.append(True)
  else:
    pred_validation.append(False)

print(calcAccuracy(target_validation,pred_validation))

0.8375


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
clf = KNeighborsClassifier(3)

In [ ]:
clf.fit(features_train,target_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [ ]:
pred_train = clf.predict(features_train)
print(calcAccuracy(target_train,pred_train))

0.9375


In [ ]:
pred_validation = clf.predict(features_validation)
print(calcAccuracy(target_validation,pred_validation))

0.85


In [ ]:
pred_validation = []
for i in range(N_validation):
  pred_validation.append(False)

print(calcAccuracy(target_validation,pred_validation))

0.7


In [ ]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(10, random_state=0)

clf.fit(features_train, target_train)

pred_validation = clf.predict(features_validation)
print(calcAccuracy(target_validation, pred_validation))

0.9


In [ ]:
true_positives = 0

for i in range(N_validation):
  if target_validation[i] == True and pred_validation[i] == True:
    true_positives += 1

print(true_positives)

18


In [ ]:
true_positives = 0
true_negatives = 0
false_positives = 0
false_negatives = 0

for i in range(N_validation):
  if target_validation[i] == True and pred_validation[i] == True:
    true_positives += 1
  if target_validation[i] == False and pred_validation[i] == False:
    true_negatives += 1
  if target_validation[i] == False and pred_validation[i] == True:
    false_positives += 1
  if target_validation[i] == True and pred_validation[i] == False:
    false_negatives += 1

print(true_positives,true_negatives,false_positives,false_negatives)

18 54 2 6


In [ ]:
accuracy = (true_positives + true_negatives) / (true_positives + true_negatives + false_positives + false_negatives)
print(accuracy)

0.9


In [ ]:
precision = true_positives / (true_positives + false_positives)
print(precision)

0.9


In [ ]:
recall = true_positives / (true_positives + false_negatives)
print(recall)

0.75


In [ ]:
f1score = 2 * (precision * recall) / (precision + recall)
print(f1score)

0.8181818181818182


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, recall_score, precision_score

pred_test = clf.predict(features_test)

In [ ]:
print(confusion_matrix(target_test,pred_test))

[[62  3]
 [ 5 30]]


In [ ]:
print("accuracy_score:", accuracy_score(target_test,pred_test))
print("f1_score:", f1_score(target_test,pred_test))
print("recall_score:", recall_score(target_test,pred_test))
print("precision_score:", precision_score(target_test,pred_test))

accuracy_score: 0.92
f1_score: 0.8823529411764706
recall_score: 0.8571428571428571
precision_score: 0.9090909090909091


In [ ]:
import pickle

with open('saved_classifier.pickle','wb') as f:
  pickle.dump(clf,f)

In [ ]:
with open('saved_classifier.pickle','rb') as f:
  clf = pickle.load(f)